apiVersion: apps/v1
kind: Deployment #Oluşturduğumuz Kubernetes kaynak türü
metadata:
  name: helloworld
spec:
  replicas: 2 #Bu dağıtım için oluşturulacak kopya sayısı
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: agcaaekrem/docker-demo #Cluster'da kullanılacak image dosyası 
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1 #Kubernetes API versiyonu
kind: Service  #Oluşturduğumuz Kubernetes kaynak türü
metadata:      #Oluşturduğumuz kaynak türünün meta verileri
  name: helloworld
spec:
  type: NodePort # Servisin türü
  ports:
    - port:    #Servisin kümede çalıştığı bağlantı noktası
      targetPort: 8080
  selector:
    app: helloworld
